Python/APP_GPS/urls.py
from django.urls import path
from .views import index, gps, abordagem, di, speech, fechamento, live, referidos

app_name = 'APP_GPS'

urlpatterns = [
    path('', index, name='index'),
    path('gps/', gps, name='gps'),
    path('abordagem/', abordagem, name='abordagem'),
    path('di/', di, name='di'),
    path('speech/', speech, name='speech'),
    path('fechamento/', fechamento, name='fechamento'),
    path('live/', live, name='live'),
    path('referidos/', referidos, name='referidos'),
]

Python/Projeto_GPS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('APP_GPS.urls')),
    path('APP_GPS/', include('APP_GPS.urls'))
]

Python/APP_GPS/models.py
from django.db import models

# Create your models here.

Python/APP_GPS/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    template_html = 'index.html'
    return render(request, template_html)


def gps(request):
    template_html = 'gps.html'
    return render(request, template_html)


def abordagem(request):
    template_html = 'abordagem.html'
    return render(request, template_html)


def di(request):
    template_html = 'di.html'
    return render(request, template_html)


def speech(request):
    template_html = 'speech.html'
    return render(request, template_html)


def fechamento(request):
    template_html = 'fechamento.html'
    return render(request, template_html)


def live(request):
    template_html = 'live.html'
    return render(request, template_html)


def referidos(request):
    template_html = 'referidos.html'
    return render(request, template_html)

Python/APP_GPS/templates/di.html
{% extends 'base_admin.html' %}
{% block title %} WSR {% endblock title %}
{% load static %}
{% block content %}

<!-- Inicio HTML -->
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-6 col-md-6">
                <!-- Contadores -->
                <div class="row">
                    <!-- DI -->
                    <div class="col-xl-12 col-md-12 mb-1 ml-2">
                        <a href="#" class="card-link">
                            <div class="card border-left-info shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xxl font-weight-bold text-info text-uppercase mb-1">DI
                                            </div>
                                            <div class="row no-gutters align-items-center">
                                                <div class="col">
                                                    <div class="progress progress-sm mr-2">
                                                        <div class="progress-bar bg-info" role="progressbar"
                                                            style="width: 0%" aria-valuenow="0" aria-valuemin="0"
                                                            aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-hourglass-half fa-2x text-black-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- Fim DI -->
                </div>
                <!-- Fim Contadores -->

                <!-- Botões -->
                <div class="row">
                    <div class="row justify-content-between ml-0">
                        <div class="card-text accordion text-Left ml-4" id="accordion_di">


                                <!-- Caixa de seleção personalizada -->
                                <div class="custom-control custom-checkbox my-2">
                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                    <label class="custom-control-label" for="customCheck">
                                        <div class="btn btn-success btn-icon-split" data-toggle="collapse" data-target="#texto_di">
                                            <span class="icon text-white-50">
                                                <i class="fas fa-check"></i>
                                            </span>
                                            <span class="text">DECISÃO IMEDIATA</span>
                                        </div>
                                    </label>
                                </div>
                                <!-- Caixa de seleção personalizada -->
                                <div class="custom-control custom-checkbox my-2">
                                    <input type="checkbox" class="custom-control-input" id="customCheckI">
                                    <label class="custom-control-label" for="customCheckI">
                                        <div class="btn btn-success btn-icon-split" data-toggle="collapse" data-target="#combinado">
                                            <span class="icon text-white-50">
                                                <i class="fas fa-check"></i>
                                            </span>
                                            <span class="text">COMBINADO????</span>
                                        </div>
                                    </label>
                                </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-6 col-md-5">
                <!-- Texto oculto -->
                <div class="row">
                    <div class="card shadow text-left">
                        <!-- Card DI -->
                        <div id="texto_di" class="collapse">
                            <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Texto DI</h6>
                                <div class="dropdown no-arrow">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuI"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                        aria-labelledby="dropdownMenuLink">
                                        <div class="dropdown-header">Opções:</div>
                                        <a class="dropdown-item" href="#">Editar</a>
                                        <a class="dropdown-item" href="#">Deletar</a>
                                    </div>
                                </div>
                            </div>
                            <div class="card card-body">
                                <p class="card-text">
                                    Então Fulano(a), entendi sua necessidade em aprender inglês,
                                    agora vou te explicar a metodologia e os valores da nossa plataforma,
                                    mas antes eu preciso firmar um compromisso bem simples contigo,
                                    um compromisso de objetividade. Se você não gostar da metodologia,
                                    ou o valor não couber no seu orçamento no momento,
                                    eu quero te deixar a vontade para me falar não, não gostei,
                                    ou não posso estar fazendo o curso no momento, mas em contra partida,
                                    se for o que você está procurando, e é algo que você quer fazer nesse
                                    momento a gente finaliza sua matrícula agora nessa ligação, combinado?
                                    <<< ESPERA O LEAD RESPONDER >>>
                                    Combinado então
                                </p>
                            </div>
                        </div>



                        <!-- Card DI -->
                        <div id="combinado" class="collapse">
                            <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Combinado!</h6>
                                <div class="dropdown no-arrow">
                                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuII"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                                        aria-labelledby="dropdownMenuLink">
                                        <div class="dropdown-header">Opções:</div>
                                        <a class="dropdown-item" href="#">Editar</a>
                                        <a class="dropdown-item" href="#">Deletar</a>
                                    </div>
                                </div>
                            </div>
                            <div class="card card-body">
                                <p class="card-text">
                                    A DI deve ser clara e o lead responder COMBINADO!
                                </p>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Botões inferiores -->
    <div class="position-fixed fixed-bottom text-center mb-5">
    <!-- Botão "Desligou" -->
        <div class="col-xl-2 col-md-2 mb-5 d-inline-block">
          <a href="{% url 'APP_GPS:gps' %}" class="card-link">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Desligou</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-phone-slash fa-2x"></i>
                        </div>
                    </div>
                </div>
            </div>
          </a>
        </div>

        <!-- DI -->
        <div class="col-xl-3 col-md-3 mb-5 d-inline-block">
          <a href="{% url 'APP_GPS:speech' %}" class="card-link">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xxl font-weight-bold text-primary text-uppercase mb-1">SPEECH</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-arrow-right fa-2x"></i>
                        </div>
                    </div>
                </div>
            </div>
          </a>
        </div>
    </div>
    <!-- Final botões inferiores -->


        <!-- Final html -->
</body>

<!-- Adicione este script modificado -->
<script>
  // Variáveis
  const durations = [60, 0]; // Durações em segundos para cada barra de progresso
  const progressBars = document.querySelectorAll('.progress-bar');
  const cards = document.querySelectorAll('.card-link');

  let cardIndex = 0;
  let elapsedSeconds = 0;
  let interval;

  // Função para atualizar a barra de progresso
  function updateProgressBar() {
    elapsedSeconds++;
    const progressPercentage = (elapsedSeconds / durations[cardIndex]) * 100;
    progressBars[cardIndex].style.width = progressPercentage + '%';
    if (elapsedSeconds >= durations[cardIndex]) {
      clearInterval(interval);
      cardIndex++; // Avance para o próximo card
      if (cardIndex < cards.length) {
        startCountdown(); // Inicie o contador para o próximo card
        // Mostra a div oculta do card atual e oculta as outras
        cardTexts.forEach((text, index) => {
          if (index === cardIndex) {
            text.style.display = 'block';
          } else {
            text.style.display = 'none';
          }
        });
      }
    }
  }



  // Função para iniciar o contador
  function startCountdown() {
    elapsedSeconds = 0;
    progressBars[cardIndex].style.width = '0%';
    interval = setInterval(updateProgressBar, 1000);
  }


  // Adicionar um evento de clique para cada card
  cards.forEach((card, index) => {
    card.addEventListener('click', () => {
      if (cardIndex === index) {
        // Se o card clicado for o mesmo em andamento
        clearInterval(interval); // Limpa o intervalo atual
        elapsedSeconds = durations[cardIndex]; // Define o tempo decorrido como a duração para preencher a barra
        updateProgressBar(); // Atualiza a barra de progresso
      }
    });
  });



  // Iniciar o contador quando a página carregar (inicie com o primeiro card)
  startCountdown();



    // Recolher os botões não clicados
      document.querySelectorAll('.btn[data-toggle="collapse"]').forEach(function (btn) {
        btn.addEventListener('click', function () {
            const target = document.querySelector(btn.getAttribute('data-target'));
            const allCollapses = document.querySelectorAll('.collapse');
            allCollapses.forEach(function (collapse) {
                if (collapse !== target) {
                    $(collapse).collapse('hide');
                }
            });
        });
    });


</script>



<!-- Fim HTML -->

{% endblock content %}

Python/APP_GPS/templates/gps.html
{% extends 'base_admin.html' %}
{% block title %} WSR {% endblock title %}
{% load static %}
{% block content %}


<!-- Inicio HTML -->
<body>
            <!-- Card - Chamando -->
            <div class="row">
                <!-- DI -->
                <div class="col-xl-6 col-md-6 mx-auto mt-3">
                    <a href="#" class="card-link">
                        <div class="card border-left-info shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xxl font-weight-bold text-info text-uppercase mb-1">CHAMANDO
                                        </div>
                                        <div class="row no-gutters align-items-center">
                                            <div class="col">
                                                <div class="progress progress-sm mr-2">
                                                    <div class="progress-bar bg-info" role="progressbar"
                                                        style="width: 0%" aria-valuenow="0" aria-valuemin="0"
                                                        aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-headset fa-2x text-black-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <!-- Fim Card - Chamando -->
            <!-- Botões inferiores -->
            <div class="position-fixed fixed-bottom text-center mb-5 ml-5">
            <!-- Botão "NÃO ATENDEU" -->
                <div class="col-xl-2 col-md-2 mb-5 d-inline-block">
                  <a href="{% url 'APP_GPS:gps' %}" class="card-link">
                    <div class="card border-left-danger shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">NÃO ATENDEU</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-phone-slash fa-2x"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                  </a>
                </div>

                <!-- ATENDEU -->
                <div class="col-xl-3 col-md-6 mb-5 d-inline-block">
                  <a href="{% url 'APP_GPS:abordagem' %}" class="card-link">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xxl font-weight-bold text-primary text-uppercase mb-1">ATENDEU</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-arrow-right fa-2x"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                  </a>
                </div>
            </div>
            <!-- Final botões inferiores -->
</body>
<!-- Fim HTML -->

<!-- Script JS -->
<script>

  // Variáveis
  const duration = 60; // Duração em segundos para barra de progresso
  const progressBars = document.querySelectorAll('.progress-bar');
  const cards = document.querySelectorAll('.card-link');

  let cardIndex = -1;
  let elapsedSeconds = 0;
  let interval;

  // Função da barra de progresso
  function updateProgressBar() {
    elapsedSeconds++;
    const progressPercentage = (elapsedSeconds / duration) * 100;
    progressBars[cardIndex].style.width = progressPercentage + '%';
    if (elapsedSeconds >= duration) {
      clearInterval(interval);
      cardIndex++; // incremento para próximo card
      if (cardIndex < cards.length) {
        startCountdown(); // Inicie o contador para o próximo card
        // Mostra a div oculta do botão clicad e oculta as outras
        cards.forEach((card, index) => {
          if (index === cardIndex) {
            card.style.display = 'block';
          } else {
            card.style.display = 'none';
          }
        });
      }
    }
  }

  // Função para iniciar o contador
  function startCountdown() {
    elapsedSeconds = 0;
    progressBars[cardIndex].style.width = '0%';
    interval = setInterval(updateProgressBar, 1000);
  }

  // Inicia o contador ao clicar no card
  cards.forEach((card, index) => {
    if (index === 0) {
      card.addEventListener('click', () => {
        if (cardIndex === -1) { // Inicie o contador apenas se ainda não foi iniciado
          cardIndex = 0;
          startCountdown(); // Inicie o contador
        }
      });
    }
  });

</script>


{% endblock content %}

Python/APP_GPS/templates/index.html
{% extends 'base_admin.html' %}
{% block title %} WSR {% endblock title %}
{% load static %}
{% block content %}
    <!-- Cabeçalho -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">

        <h1 class="h3 mb-0 text-gray-800"></h1>

        <a href="{% url 'APP_GPS:gps' %}" class="btn btn-primary btn-icon-split btn-lg">
        <span class="icon text-white-50">
        <i class="fas fa-phone"></i>
        </span>
        <span class="text">GPS's</span>
        </a>

        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Baixar relatório</a>
    </div>
<!-- Inicio cartões -->
    <!-- Content Row -->
    <div class="row">
        <!-- Ligações na semana -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Ligações na semana</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">600</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Vendas no mês -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Vendas Mês
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">48</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar"
                                            style="width: 80%" aria-valuenow="50" aria-valuemin="0"
                                            aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Leads no mês -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Leads</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">86</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Leads sem tabular -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Leads sem tabular</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Final cartões -->

    <!-- Content Row -->
    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-6">

            <!-- Metas -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Metas do dia</h6>
                </div>
                <div class="card-body">
                    <h4 class="small font-weight-bold">Leads do dia <span
                            class="float-right">60%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 60%"
                            aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Vendas da semana <span
                            class="float-right">66%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 66%"
                            aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Leads sem tabular <span
                            class="float-right">26%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar" role="progressbar" style="width: 26%"
                            aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Retornos <span
                            class="float-right">92%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 92%"
                            aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Tempo de ligação <span
                            class="float-right">00:46 01:00</span></h4>
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 92%"
                            aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <!-- Motivações -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Motivações</h6>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 18rem;"
                            src="{% static 'img/undraw_super_woman_dv-0-y.svg' %}" alt="...">
                    </div>
                    <p>Aqui uma mensagem que irá te motivar: VOCÊ PODE MUITO!</p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}